import { useForm } from 'react-hook-form'
import { XMarkIcon } from '@heroicons/react/24/outline'

const currentMonth = () => new Date().toISOString().slice(0, 7)

function BudgetModal({ budget, loading, onClose, onSubmit }) {
  const editing = Boolean(budget)
  const { register, handleSubmit, formState: { errors } } = useForm({ defaultValues: budget ? { monthlyLimit: budget.monthlyLimit, budgetMonth: budget.budgetMonth } : { monthlyLimit: '', budgetMonth: currentMonth() } })

  const submit = (values) => onSubmit({ monthlyLimit: Number(values.monthlyLimit), budgetMonth: values.budgetMonth })
  return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/45 p-4 sm:grid sm:place-items-center" role="dialog" aria-modal="true" aria-labelledby="budget-modal-title"><section className="my-6 w-full max-w-lg rounded-2xl bg-white p-5 shadow-2xl sm:my-0 sm:p-6"><div className="flex items-start justify-between gap-4"><div><h2 id="budget-modal-title" className="text-xl font-bold text-slate-950">{editing ? 'Edit budget' : 'Create budget'}</h2><p className="mt-1 text-sm text-slate-500">Set a monthly spending limit that works for you.</p></div><button onClick={onClose} disabled={loading} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Close budget modal"><XMarkIcon className="size-5" /></button></div><form onSubmit={handleSubmit(submit)} className="mt-6 grid gap-4"><label><span className="mb-1.5 block text-sm font-semibold text-slate-700">Monthly budget</span><input type="number" step="0.01" min="0.01" {...register('monthlyLimit', { required: 'Monthly budget is required', valueAsNumber: true, min: { value: 0.01, message: 'Budget must be greater than zero' } })} placeholder="0.00" className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100" />{errors.monthlyLimit && <span className="mt-1 block text-xs font-medium text-rose-600">{errors.monthlyLimit.message}</span>}</label><label><span className="mb-1.5 block text-sm font-semibold text-slate-700">Budget month</span><input type="month" {...register('budgetMonth', { required: 'Budget month is required' })} disabled={editing} className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-100 disabled:bg-slate-100" />{errors.budgetMonth && <span className="mt-1 block text-xs font-medium text-rose-600">{errors.budgetMonth.message}</span>}{editing && <span className="mt-1 block text-xs text-slate-500">The month cannot be changed for an existing budget.</span>}</label><div className="flex justify-end gap-3 pt-2"><button type="button" onClick={onClose} disabled={loading} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-100">Cancel</button><button type="submit" disabled={loading} className="rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-700 disabled:opacity-60">{loading ? 'Saving…' : editing ? 'Save changes' : 'Create budget'}</button></div></form></section></div>
}

export default BudgetModal
