import { useForm } from 'react-hook-form'
import { XMarkIcon } from '@heroicons/react/24/outline'
import { formatCurrency } from '../../utils/dashboardData'

function GoalContributionModal({ goal, loading, onClose, onSubmit }) {
  const { register, handleSubmit, formState: { errors } } = useForm({ defaultValues: { amount: '' } })
  const submit = (values) => onSubmit(Number(values.amount))
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4" role="dialog" aria-modal="true" aria-labelledby="contribution-modal-title"><section className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><h2 id="contribution-modal-title" className="text-xl font-bold text-slate-950">Add money</h2><p className="mt-1 text-sm text-slate-500">Add a contribution to {goal.title}.</p></div><button onClick={onClose} disabled={loading} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Close contribution modal"><XMarkIcon className="size-5" /></button></div><p className="mt-5 rounded-xl bg-violet-50 px-4 py-3 text-sm text-violet-800">{formatCurrency(goal.remainingAmount)} remaining to reach this goal.</p><form onSubmit={handleSubmit(submit)} className="mt-5"><label><span className="mb-1.5 block text-sm font-semibold text-slate-700">Contribution amount</span><input autoFocus type="number" step="0.01" min="0.01" {...register('amount', { required: 'Amount is required', valueAsNumber: true, min: { value: 0.01, message: 'Amount must be greater than zero' } })} className="w-full rounded-xl border border-slate-200 px-3 py-3 text-sm outline-none focus:border-violet-500 focus:ring-4 focus:ring-violet-100" />{errors.amount && <span className="mt-1 block text-xs font-medium text-rose-600">{errors.amount.message}</span>}</label><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} disabled={loading} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-100">Cancel</button><button type="submit" disabled={loading} className="rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-violet-700 disabled:opacity-60">{loading ? 'Adding…' : 'Add money'}</button></div></form></section></div>
}
export default GoalContributionModal
