import { BanknotesIcon, PencilSquareIcon, TrashIcon } from '@heroicons/react/24/outline'
import { formatCurrency, formatTransactionDate } from '../../utils/dashboardData'
import GoalProgress from './GoalProgress'

function GoalCard({ goal, onContribute, onEdit, onDelete }) {
  const completed = goal.status === 'COMPLETED'
  return <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm shadow-slate-900/3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate text-lg font-bold text-slate-900">{goal.title}</h3><p className="mt-1 text-sm text-slate-500">{goal.description || 'Savings goal'}</p></div><span className={`shrink-0 rounded-full px-2.5 py-1 text-xs font-bold ${completed ? 'bg-emerald-100 text-emerald-700' : 'bg-violet-100 text-violet-700'}`}>{completed ? 'Completed' : 'Active'}</span></div><div className="mt-6 grid grid-cols-2 gap-4 text-sm"><div><p className="text-slate-500">Saved</p><p className="mt-1 font-bold text-slate-900">{formatCurrency(goal.savedAmount)}</p></div><div><p className="text-slate-500">Target</p><p className="mt-1 font-bold text-slate-900">{formatCurrency(goal.targetAmount)}</p></div><div><p className="text-slate-500">Remaining</p><p className="mt-1 font-bold text-slate-900">{formatCurrency(goal.remainingAmount)}</p></div><div><p className="text-slate-500">Target date</p><p className="mt-1 font-semibold text-slate-700">{goal.targetDate ? formatTransactionDate(goal.targetDate) : 'Not set'}</p></div></div><div className="mt-6"><GoalProgress percentage={goal.progressPercentage} /></div><div className="mt-5 flex flex-wrap justify-end gap-2"><button onClick={() => onContribute(goal)} disabled={completed} className="inline-flex items-center gap-1.5 rounded-xl bg-violet-600 px-3 py-2 text-sm font-semibold text-white hover:bg-violet-700 disabled:cursor-not-allowed disabled:opacity-50"><BanknotesIcon className="size-4" /> Add money</button><button onClick={() => onEdit(goal)} className="rounded-xl p-2 text-slate-500 hover:bg-slate-100" aria-label={`Edit ${goal.title}`}><PencilSquareIcon className="size-5" /></button><button onClick={() => onDelete(goal)} className="rounded-xl p-2 text-rose-500 hover:bg-rose-50" aria-label={`Delete ${goal.title}`}><TrashIcon className="size-5" /></button></div></article>
}
export default GoalCard
