FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends tesseract-ocr \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /app/target/*.jar app.jar

COPY src/main/resources/tessdata /app/tessdata

ENV TESSDATA_PREFIX=/app/tessdata

EXPOSE 10000

ENTRYPOINT ["java", "-jar", "app.jar"]