import { ArrowTrendingDownIcon, ArrowTrendingUpIcon, EllipsisHorizontalIcon } from '@heroicons/react/24/outline'
const transactions = [
  { name: 'Fresh Basket', category: 'Groceries', date: 'Today, 10:24 AM', amount: '-₹1,280', type: 'expense', initials: 'FB' },
  { name: 'Monthly Salary', category: 'Income', date: 'Jul 15, 9:00 AM', amount: '+₹85,000', type: 'income', initials: 'MS' },
  { name: 'Netflix', category: 'Entertainment', date: 'Jul 14, 8:30 PM', amount: '-₹649', type: 'expense', initials: 'N' },
  { name: 'Uber', category: 'Transport', date: 'Jul 13, 7:15 PM', amount: '-₹340', type: 'expense', initials: 'U' },
]
function RecentTransactions() { return <section className="rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-900/3"><div className="flex items-center justify-between p-5 sm:p-6"><div><h2 className="font-bold text-slate-950">Recent transactions</h2><p className="mt-1 text-sm text-slate-500">Your latest money movements.</p></div><button className="text-sm font-semibold text-emerald-600 hover:text-emerald-700">View all</button></div><div className="divide-y divide-slate-100">{transactions.map((transaction) => { const income = transaction.type === 'income'; return <article key={`${transaction.name}-${transaction.date}`} className="flex items-center gap-3 px-5 py-4 sm:px-6"><span className={`grid size-10 shrink-0 place-items-center rounded-xl text-xs font-bold ${income ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{transaction.initials}</span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><h3 className="truncate text-sm font-semibold text-slate-800">{transaction.name}</h3><p className={`text-sm font-bold ${income ? 'text-emerald-600' : 'text-slate-800'}`}>{transaction.amount}</p></div><div className="mt-1 flex items-center justify-between gap-3"><p className="truncate text-xs text-slate-500">{transaction.category} · {transaction.date}</p><span className={income ? 'text-emerald-500' : 'text-rose-500'}>{income ? <ArrowTrendingUpIcon className="size-4" /> : <ArrowTrendingDownIcon className="size-4" />}</span></div></div></article> })}</div><button className="flex w-full items-center justify-center gap-1 border-t border-slate-100 py-3 text-sm font-semibold text-slate-500 hover:bg-slate-50"><EllipsisHorizontalIcon className="size-5" /> See all transactions</button></section> }
export default RecentTransactions
